spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/league_of_legends_universe_db
    username: root
    password: 123456789
server:
    port: 8089
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapperxml/*.xml

logging:
  file:
    name=CONSOLE: